import {AppRegistry} from 'react-native';
import 'react-native-gesture-handler';
import App from './App';
import {name as appName} from './app.json';
import signup from './Signup';
import Splash from './Splash';
//import Route from './Routenavigator';
import Main from './Main';
import Background from './background';
import MPA from './App';
import Login from './Login';
AppRegistry.registerComponent(appName, () => Background);
